Update greetings.yml
ajharry69/xently-shopping-mobile pull request #38
Opened 2023-09-15 17:24 UTC by rashikolhapure

### Changes made:
Fixes #

- -Changed "this a issue" to "an issue".
- -Used "respond promptly" for a smoother phrase than "get back on time". -Removed the repetitive "it is this is" to just "this is". --Added a period after "repository".
- -Changed "valued contributes" to "valuable contributions".

2023-09-15 19:21 UTC, ajharry69 requested changes

2023-09-15 19:21 UTC, ajharry69 commented on .github/workflows/greetings.yml
> +          pr-message: "Hello new contributor! We noticed this is your first PR in this repository. We will take a look at it ASAP. Thanks for your valuable contributions and for showing interest in t
Please paraphrase the statement to:

> Welcome to the project, new contributor! We appreciate your first pull request (PR) and will review it as soon as possible. Thank you for your interest in this project and your valuable contributions.

2023-09-15 19:21 UTC, ajharry69 commented on .github/workflows/greetings.yml
> +          issue-message: "Hello new contributor! Thanks for taking the time to file an issue in the repository. We will do our best to respond promptly."
Please paraphrase the statement to:

> Thank you for filing an issue in the repository. We appreciate your feedback and will do our best to respond promptly.

2023-09-16 03:53 UTC, rashikolhapure reviewed
Updated the messages.

2023-09-16 08:54 UTC, ajharry69 approved these changes

2023-09-16 09:07 UTC, merged